/* DO NOT EDIT THIS FILE - it is machine generated */
//rpi
#include "/usr/lib/jvm/jdk-7-oracle-armhf/include/jni.h"
//pc 
//#include "/usr/lib/jvm/default-java/include/jni.h"

/* Header for class Sender */

#ifndef _Included_RpiServerMain
#define _Included_RpiServerMain
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RpiServerMain
 * Method:    sendImageForProcessing
 * Signature: ([BLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_RpiServerMain_sendImageForProcessing
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     RpiServerMain
 * Method:    setImageReadyListener
 * Signature: (LImageReadyListener;)V
 */
JNIEXPORT void JNICALL Java_RpiServerMain_setImageReadyListener
  (JNIEnv *, jclass, jobject);

/*
 * Class:     RpiServerMain
 * Method:    getProcessedImage
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_RpiServerMain_getProcessedImage
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
